# Generated by Django 3.1.5 on 2021-01-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.IntegerField()),
                ('Date_birth', models.DateTimeField(verbose_name='date of birth')),
                ('zip_code', models.IntegerField()),
                ('street', models.CharField(max_length=120)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
            ],
        ),
    ]
