# Generated by Django 3.1.5 on 2021-01-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Date_birth',
            new_name='date_birth',
        ),
    ]
