# Generated by Django 3.1.5 on 2021-01-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0002_auto_20210127_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
