# Generated by Django 3.1.5 on 2021-01-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0003_auto_20210126_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
    ]
