# Generated by Django 3.1.5 on 2021-01-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0004_auto_20210126_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(verbose_name='date of birth'),
        ),
    ]
