# Generated by Django 3.1.5 on 2021-01-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0005_auto_20210126_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair', models.CharField(default='Cabelo', max_length=120)),
                ('beard', models.CharField(default='Barba', max_length=120)),
                ('sealing', models.CharField(default='Selagem', max_length=120)),
            ],
        ),
    ]
