# Generated by Django 3.1.5 on 2021-01-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barb', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('tel', models.IntegerField()),
            ],
        ),
    ]
